### PR TITLE
Add debugging menuitem with ablility to read data structures and reloadui

### PR DESCRIPTION
**Pull request by Gaisberg**

### CODE REVIEW

**Comment by CuteOne** [comment]
That's interesting but most of us just use the addon Table Explorer, assuming I'm understanding this from the brief glance through.

**Comment by kuukuukuatchu** [comment]
I thought Table Explorer was broke last I tried to use it...

**Comment by CuteOne** [comment]
Been working for me

**Comment by Gaisberg** [comment]
I had no idea there was such an addon 👍  Well I guess this in redundant then, atleast I learnt something...

**Comment by kuukuukuatchu** [comment]
hmmmm, maybe I broke something then.  But I'll close this then and learning stuff is always worth it 👍

**Pull request closed without merging**
