### PR TITLE
Mm profiletweaks

### PR DESCRIPTION
**Pull request by Bigsie**

### CODE REVIEW

**Comment by CuteOne** [comment]
There's API for canUseItem and useItem

**Comment by Bigsie** [comment]
> There's API for canUseItem and useItem

Im not following, what do you mean by this? hasEquiped is useless?

**Comment by CuteOne** [comment]
System/API

**Comment by Bigsie** [comment]
> System/API

Eyy, thats cool. Modifying it right now

**Comment by CuteOne** [comment]
My soul thanks you.

**Pull request merged**
