### PR TITLE
Add Laksmackts cc logic with some tweaks

### PR DESCRIPTION
**Pull request by Bigsie**

### CODE REVIEW

**Comment by Gaisberg** [comment]
Tested in plaguefall, worked OK

**Comment by Bigsie** [comment]
Test in mots, worked OK

**Comment by kuukuukuatchu** [comment]
Why remove conduit and equiped locals?  That would serve no purpose at all.

**Comment by Bigsie** [comment]
They werent used, atleast according to my lua intellisense.

**Comment by Bigsie** [comment]
> Why remove conduit and equiped locals? That would serve no purpose at all.

They werent used, atleast according to my lua intellisense.

**Comment by CuteOne** [comment]
It's possible they will be in the future, especially conduit, but it's not like it can't be re-added. My only issue is why is this needed and not handled at system level.

**Comment by Bigsie** [comment]
So if I elevate it to system level so that all profiles can reak the benefits? 
To answer why its needed: Well, its just a bit more automation that makes BadRotations godly :) I can also keep these personal if you guys dont find them useful.

**Comment by Bigsie** [comment]
Closing due to lots of incomming changes still...

**Pull request closed without merging**
