### PR TITLE
Mmhunter cc and stuff

### PR DESCRIPTION
**Pull request by Bigsie**

### CODE REVIEW

**Comment by CuteOne** [comment]
Main issue with this now is the string matching, does GetZoneText always return english values or are they localized? If localized probably should match via zone id.

**Comment by Bigsie** [comment]
> Main issue with this now is the string matching, does GetZoneText always return english values or are they localized? If localized probably should match via zone id.

Good point. I however still dont like this, I need to specify criterias for CC's not just blindly CC out of cooldown. Any ideas?

**Comment by Bigsie** [comment]
Now im not touching it anymore... Any other comments? @CuteOne

**Comment by Bigsie** [comment]
Closing this for less commits in one PR merge as I dont know how to squash commits in PR's

**Pull request closed without merging**
